### ISSUE TITLE
Teacher - Create Collection

### ISSUE THREAD

**Issue by mateoclarke** [civicparty/legitometer#20]

**Comment by mateoclarke** [comment]
![screen shot 2017-06-15 at 6 01 07 pm](https://user-images.githubusercontent.com/5697474/27205164-d8569a70-51f4-11e7-9aa3-9e04bdd0e583.png)

last thing left...

on "Save Case File"
save case file and mission
redirect user to mission show page

**Comment by rallyjinx** [comment]
Done! Except for the redirect.

**Comment by rallyjinx** [comment]
Completed
