### ISSUE TITLE
July 16 Team Meeting Agenda

### ISSUE THREAD

**Issue by mateoclarke** [civicparty/legitometer#54]
- introducing Rally to the team
- show Sarah what we have locally since the database connection issue on the test site is unresolved. 
- Refresh with Sean on what design work is ahead and what we need to catch up on. Probably a good place to talk about evaluation for teachers and social for students
- Set new milestones, PD w/ AISD etc.
- Mozilla hosting, looping in Hannah Kane

**Comment by mateoclarke** [comment]
Dev TODOs:
- [ ] on `/start` page don't limit the messaging to 3
- [ ] warn the user that we'll be opening the article in a new tab
- [ ] Change OK on button to "Next"
- [ ] show next question in gray at bottom of page. 
- [ ] Animate the page to shift up when you like "Next"
- [ ] Before the start section. have the student(s) input the names of ppl in their group.
- [ ] Drop the randomness of articles. Just go in order of the one's they added.
- [ ] Buy Legit or not.org
- [ ] Adding a place on the teacher side for city, school

Design TODOs:
- Evaluation: designing the teacher evaluation page
    - rubric from the Teacher.
    - Q: how do we cluster ppl? A: default is in group
    - How google Form shows it as a spreadsheet, cleaner individual view. See the responses in aggregate, or individual.
    - Idea: visualize response in graph form.
    - Teacher could share the evaluation form on a screen in front of the classes as the starting point for why each group thought each article for fake or legit.
- Social, making the student experience social: 
   - Social media is out of the question the classroom setting.
   - getting immediate feedback is important
   - On the last page: 
       1. You thought the article is: 1. Fake news, 2. Might be fake news 3. Probably legit news. 4. Totally legit news. 
      2. According to your teacher, this article is: (match what the students have above). 
      3. Table the idea of displaying other student reviews to the group upon completion. Let the teachers show the comparison in their evaluation.
- Changing mascot bc of Grumpy Cat trademark

<img width="606" alt="screen shot 2017-07-16 at 12 53 27 pm" src="https://user-images.githubusercontent.com/5697474/28250004-d53fdf6a-6a25-11e7-9e99-13e207b43a01.png">


Social idea: public facing page that shows results collectively of articles. Back to the Yelp for News idea.

Milestones:
- Design Deliverables 1: July 19th, Sean
   1. Student final page
   2. Teacher evaluation summary
   3. Teacher single group evaluation
- Dev Deliverables 1: July 30, Mateo & Rally
- Pre-AISD Training checkin:  August 1st, 5:30pm
- AISD Training: August 2nd & 3rd: 1:20 minutes one day, 1 hour the next. High level introduction. Teacher's should come away with an action plan of how to use this. 3 lessons to introduce. Having a legit o meter that works (Sarah says ok if certain features aren't working). There will a lot to cover.
- First Day of Classes at AISD: Aug 21st, incorporate feedback out of session. Target some kind of marketing announcement. Gigabit newsletter etc
- End of Grant Period: September 30
- Grant Report: October
- Hackathon: December

**Comment by secmorris** [comment]
Legit-O-Meter Questions from Sarah  
[](https://goo.gl/forms/fG4IMzhv9N0MdOOA3 )

Intro helper text - Work as a team and use skim reading skills to help you evaluate the article and see if it is credible! Remember, you'll be looking at context clues and digging for information to help you better understand the article.

Questions
What is the headline? 
Helper text - none 
Type: short answer 

Briefly summarize the article in 1 sentence. 
Helper text - Tip: Use your skim reading skills here! Remember, you want to quickly get a sense of what the article is about. Try reading the first and last paragraphs, take turns reading aloud in your group, or look for a thesis statement. 
Type: long answer 

Section header - Author and Publisher 
Helper text - For these questions you'll find out information about the author and publisher. Tip: divide up tasks among the team! One person can write down notes while other conduct research. 

Questions
What is the author's name? 
Helper text - none
Type - short answer

What information can you find about the author?
Helper text - Tip: Look for information about what the author has written before and what their qualifications are. Try a Google search here! 
Type- long answer

Is the author credible? 
Helper text - none
Type - yes or no 

Who published this article? 
Helper text - Tip: look for the title of the magazine, newspaper, or website where you found your article 
Type  - short answer

What information can you find about the publisher? 
Helper text - Tip: Look for information about the publication and its reputation. Has the publication won awards? What do people say about it? 
Type - long answer

Is the publisher credible? 
Helper text - none
Type  - yes or no

Section header - Context
Helper text - Here you will answer some questions about the website and about features of the article. 

Questions
Is the site well designed? 
Helper text - none
Type - yes or no

Design information - what did you notice?  
Helper text - Tip: were there spelling errors? Layout problems? Does the site look nice and work well? 
Type  - long answer

Did the author use sources in the article? 
helper text - none
type - yes or no

Where did the sources come from? 
helper text - Tip: Check out the links, if there are any, in the article. Or see if the article quotes anyone. 
type - long answer

What year was the article published? 
helper text- none
type - short answer

Section header - Bias and Purpose
helper text - For these questions you'll dig into some "why" questions - why did someone write this article? What is the goal of the article? And does the article have bias, or lean a certain way on an issue? Remember, bias isn't inherently good or bad! 

Questions
Is there bias in your article? 
helper text - none
type - yes or no

What did you notice about bias in this article? Is the author trying to make you believe something?
helper text - Remember, bias means leaning one way or another on an issue. Is the article for or against something? Is the article trying to convince you to take a side on an issue? 
type - long answer

What is the purpose of the article? Why was it produced?
helper text - Tip: Think about the article's goal. Is the article trying to persuade you to think a certain way, make you laugh, give you facts? 
type - long answer

Section header - Final Scorecard - Rate the article!

questions
Do you think the headline accurately reflects the content in the article? 
type - yes or no

Did the article help you understand the topic better?  
type - yes or no

Would you cite this article in a research paper?  
type - yes or no

Would you share this article with someone you know or on social media?
type - yes or no

**Comment by mateoclarke** [comment]
Captured the todos in other issues. Closing this issue.
