### ISSUE TITLE
Teacher - Create a Collection

### ISSUE THREAD

**Issue by mateoclarke** [civicparty/legitometer#7]
_We were calling this a Theme but Collection is a better name._

- Teacher is required to name a Collection
- Add collections of articles. 
  - potential feature: They input a URL. Our system detects a headline from the HTML meta data. Headline does not need to be editable.
- Teacher selects Article Type from select/dropdown
- List of Article Type Options
- Definitions for both Teachers and students of article types
- Teacher can delete a theme
- As a teacher adds articles, the form auto-saves.

Post-MVP idea: Include a guide for how to create a Theme. Suggest teachers to things like include articles from various sources. Give them recommendations on where to find misinformative articles.

https://gomockingbird.com/projects/1ai9dty/Zxs59c

![screen shot 2017-03-14 at 12 26 45 am](https://cloud.githubusercontent.com/assets/5697474/23886984/f09c9d10-084c-11e7-978a-388464f6c63f.png)

**Comment by mateoclarke** [comment]
Need to:
- [x] Add a dropdown option for article types.
- [ ] Provide definitions for teachers for each article type.

![screen shot 2017-04-08 at 10 44 39 pm](https://cloud.githubusercontent.com/assets/5697474/24834490/f873afaa-1cac-11e7-9814-5c3eec71e342.png)

**Comment by rallyjinx** [comment]
### Update: 
Casefiles are saved with a name and a collection of articles, associated with a mission name. 

### Still do to: 
- [x] Teacher selects Article Type from select/dropdown (these have broken)
- [x] List of Article Type Options
- [ ] Definitions for both Teachers and students of article types
- [ ] Teacher can delete a casefile
- [ ] As a teacher adds articles, the form auto-saves.

**Comment by mateoclarke** [comment]
Going to add the definitions as a separate issue to revisit.
Going to tackle "Teacher can delete a casefile" as a part of the Edit page. #21 
I don't think the auto-save is necessary.
