### ISSUE TITLE
Get only one article from API

### ISSUE THREAD

**Issue by mateoclarke** [civicparty/legitometer#70]
We should write a route that allows you to grab articles by their casefile id.

EX: "/api/articles/casefile/2"

**Comment by rallyjinx** [comment]
I've written this route and there is also one that gets all the articles in a mission (by name) for the 'Review' button on the teacher dashboard. There is also the framework for a route to get an article by the article's id, if we find we need that. 

Note: there is no front-end hooked up to the '/api/articles/casefile/:id' route yet
