### ISSUE TITLE
Teacher - Mission Show page & Start a Game

### ISSUE THREAD

**Issue by mateoclarke** [civicparty/legitometer#8]
- Review step, see all the articles
- Choose to publish, which creates a public URL for the teacher to share with students. Public URL looks like “domain.com/teacher_username/game_id”
- The Game instance is given a name attribute.
- The only thing editable on this page is the Game Name.
  - Question: Is there a default name?
- Post MVP question: Should teachers be able to select which articles within a Theme/Collection they want to use within a given game

https://gomockingbird.com/projects/1ai9dty/xlOJyF

![screen shot 2017-03-14 at 12 28 14 am](https://cloud.githubusercontent.com/assets/5697474/23887022/219362e6-084d-11e7-877b-cc3813f0e494.png)

**Comment by rallyjinx** [comment]
Update: 
Review step, see all the articles
The Game instance is given a name attribute.

Still do to: 
    Choose to publish, which creates a public URL for the teacher to share with students. Public URL looks like “domain.com/teacher_username/mission_id” (url is saved /teacher_username/ so the mission_id could be appended when the 'publish' button is clicked)
I'm going to make a separate issue for this and close this one.
